#pragma once
typedef enum _STRINGS {
	STR_MPPURCHASE,
	STR_XAM,
	STR_KERNEL,
	STR_XOSC,
	STR_HUD,
	STR_SPFG,
	STR_SECDATA,
	STR_LAUNCH,
	STR_LIVEBLOCK,
	STR_LIVESTRONG,
	STR_TOKENCONFIRM,
	STR_HOST_SERVICES,
	STR_HOST_SERVICES_DBG,
	STR_HOST_GATEWAY,
	STR_PATH_DLCONFIG,
	STR_DLOPT_XHTTP,
	STR_KV,
	STR_XBDM,
	STR_DASHLAUNCH,
	STR_DEFAULT,
	STR_XEXMENU,
	STR_FXMENU,


	STR_INI_SETTINGS,
	STR_INI_BYPASSES,
	STR_INI_TEAPOTENGINE,
	STR_INI_CUSTOMUI,
	STR_INI_OFFLINE,
	STR_INI_AW,
	STR_INI_GHOSTS,
	STR_INI_BO2,
	STR_INI_BO3,
	STR_INI_GTAV,
	STR_INI_FANSPEED,


	STR_PATH_HUDSKIN,
	STR_SKIN,

	STR_HOST_CDNSERVER_CFB,
	STR_HOST_CDNSERVER,

	STR_XML_DASHHOME,
	STR_XML_ANNOUNCEMENTS,

	STR_URLDIR_MANIFESTS,
	STR_URLPATH_XMLDASHHOME,
	STR_URLPATH_XMLUPDATES,
	STR_URLPATH_GEOAPI,
	STR_URLPATH_IPAPI,
	STR_URLPATH_PARAMS_IPAPI,

	STR_DANKHAXFILE,
	STR_XNOTIFY_ANTITAMPER,

	STR_BO2_RELAY

}STRINGS;

std::string getString(STRINGS strIndex);