#ifndef __CONSOLE_TYPE_H
#define __CONSOLE_TYPE_H

typedef enum {
	CONSOLE_TYPE_XENON,
	CONSOLE_TYPE_ZEPHYR,
	CONSOLE_TYPE_FALCON,
	CONSOLE_TYPE_JASPER,
	CONSOLE_TYPE_TRINITY,
	CONSOLE_TYPE_CORONA,
	CONSOLE_TYPE_WINDCHESTER
} CONSOLE_TYPE;

#define CONSOLE_TYPE_FLAGS_MASK 	(0xF0000000)
#define CONSOLE_TYPE_FROM_FLAGS 	(XboxHardwareInfo->Flags & CONSOLE_TYPE_FLAGS_MASK)
#define IS_CONSOLE_TYPE_SLIM		(CONSOLE_TYPE_FROM_FLAGS > CONSOLE_TYPE_JASPER)

#endif // __CONSOLE_TYPE_H
